### ISSUE TITLE
Reset Ui Bookmarks does not show after install

### ISSUE THREAD

**Issue by loanrefi** [magenizr/Magenizr_Debugger#1]
Hi,

I installed your Reset Ui Bookmarks module manually and I can't get the button to reset Ui Bookmarks to show.

I did notice that it only shows up when Magento2 prompts for a password reset when the password lifetime expires.

Do you know what I can do to get the Ui Bookmarks button to show in the Admin panel?

I'm using Magento 2.3.4.
PHP 7.3.28
Ubuntu Server 20.04

Thank you,

**Comment by magenizr** [comment]
Hi @loanrefi 

Can you try again with the latest version 1.2.0 https://github.com/magenizr/Magenizr_ResetUiBookmarks ? Let me know how you go.

Cheers,
John
